name: Self-Hosted Runner Test

on: [push]

jobs:
  test:
    runs-on: [self-hosted, runner] 

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to the correct version

      # Step 2: Print runner information
      - name: Print runner information
        run: |
          echo "Runner name: $RUNNER_NAME"
          echo "Runner OS: $RUNNER_OS"
          echo "Runner architecture: $RUNNER_ARCH"

      # Step 3: Run a command
      - name: Run a command
        run: |
          echo "Hello from self-hosted runner!"
