name: Self-Hosted Runner Test
on: [push]
jobs:
  test:
    runs-on: self-hosted
    steps:
 - name: Checkout code
        uses: actions/checkout@v4
      - name: Print runner information
        run: |
          echo "Runner name: $RUNNER_NAME"
          echo "Runner OS: $RUNNER_OS"
          echo "Runner architecture: $RUNNER_ARCH"
      - name: Run a command
        run: echo "Hello from self-hosted runner!"
