name: Hello World Workflow

# Controls when the workflow will run
on:
  push:
    branches:
      - main  # Triggers the workflow on push to the main branch

# Define the jobs that will run as part of the workflow
jobs:
  say-hello:
    runs-on: self-hosted  # Specifies the environment for the job (self-hosted runner)
    
    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2
        
      # # Step 2: Print "Hello, Sohail!" to the console
      # - name: Hello World Step
      #   run: echo "Hello, Sohail !"  # Corrected this line

  say-goodbye:
    runs-on: self-hosted  # Specifies the environment for the job (self-hosted runner)
    needs: say-hello  # This ensures 'say-hello' runs before 'say-goodbye'
    
    steps:
      # Step 1: Print "Goodbye, Sohail!" to the console
      - name: Goodbye World Step
        run: echo "Goodbye, Sohail!"  # Corrected this line
